# s=set()
# print(type(s))
# num=set([1,2,3,4,5,6,7,8,9])
# print(num)
# num=[1,2,3,4,5,6,7,8,9]
# l=set(num)
# print(l)
# s.add("Satyam Empire")
# s.add("Satyam Empire")
# print(s)
# s.add("Satyam Empire")
# s.add("Shivam Tripathi")
# # s1=s.union({"Satyam Empire","Ram Tripathi","Raja Tripathi"})
# # s1=s.intersection({"Deep Tripathi","Satyam Empire","Shivam Tripathi"})
# print(s,s1)
